name: "Schedule"
description: "Execute a Schedule"
inputs:
  variable:
    description: "The Github Variable that contains the schedule JSON"
    required: true
outputs:
  schedule:
    description: "The matched schedule."
runs:
  using: "node20"
  main: "dist/index.js"
branding:
  icon: "calendar"
  color: "orange"
