name: GitHub Actions Demo

on:
  schedule:
    - cron: "15 4,5 * * *"
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  Schedule:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Schedule Branch Lock
        uses: ./
        with:
          config: ${{ vars.SCHEDULE }}
